ci: Update readme.txt Stable tag with more details.
- Update script to update Stable tag in readme.txt
- Improve error messages for invalid channels or empty latest tag
- Made changes to [.github/workflows/update-readme-txt/action.yml]

diff --git a/.github/workflows/update-readme-txt/action.yml b/.github/workflows/update-readme-txt/action.yml
--- a/.github/workflows/update-readme-txt/action.yml
+++ b/.github/workflows/update-readme-txt/action.yml
@@ -16,21 +16,38 @@ runs:
       - name: Get & Update Stable Tag In Readme.txt
         shell: bash
         run: |
-              # Get the latest ga tag e.g. 3.13.2
+              README_TXT_PATH=$GITHUB_WORKSPACE/elementor/readme.txt
               if [[ "${{ inputs.CHANNEL }}" == "cloud" || "${{ inputs.CHANNEL }}" == "beta" || "${{ inputs.CHANNEL }}" == "dev" ]]; then
+              
+                # git ls-remote --tags: This command lists all the tags in the remote repository along with their corresponding commit hash.
+                # grep -v "\-rc" | grep -v "\-cloud" | grep -v "\-dev" | grep -v "\-beta": This series of commands excludes tags that contain the specified substrings "-rc", "-cloud", "-dev", and "-beta".
+                # awk '{print $2}': This command prints the second field (i.e., the tag name) from the output of the previous command.
+                # grep -E 'v[0-9]+\.[0-9]+\.[0-9]+$': This command uses a regular expression to match tags that follow the semantic versioning pattern "vX.Y.Z", where X, Y, and Z are numbers.
+                # sort -V: This command sorts the matched tags in ascending order based on their version numbers.
+                # tail -n 1: This command selects the last (i.e., the highest) version number among the matched tags.
+                # sed 's/^refs\/tags\/v//': This command removes the leading "refs/tags/v" prefix from the selected tag name.
+
                 latest_tag=$(git ls-remote --tags | grep -v "\-rc" | grep -v "\-cloud" | grep -v "\-dev" | grep -v "\-beta" | awk '{print $2}' | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1 | sed 's/^refs\/tags\/v//')
-              fi
 
-              # Get the latest ga tag e.g. 3.13.2 from the package version in case of channel ga
-              if [[ "${{ inputs.CHANNEL }}" == "ga" ]]; then
+              elif [[ "${{ inputs.CHANNEL }}" == "ga" ]]; then
+
+                # We currently update the Stable tag in the readme.txt file only for the GA channel with the
+                # New package version. This is because the GA channel is the only channel that has a stable
+
                 latest_tag=${{ inputs.PACKAGE_VERSION }}
+
+              else
+                echo "Invalid channel: ${{ inputs.CHANNEL }}"
+                exit 1
               fi
 
-              sed -i -E "s/Stable tag: .*/Stable tag: ${latest_tag}/g" $GITHUB_WORKSPACE/elementor/readme.txt
+              if [[ -z "${latest_tag}" ]]; then
+                echo "latest_tag is empty"
+                exit 1
+              fi
 
-              echo "readme.txt updated with Stable tag: ${latest_tag}"
+              sed -i -E "s/Stable tag: .*/Stable tag: ${latest_tag}/g" $README_TXT_PATH
 
-
-              
-              
-
+              echo "Readme.txt updated with Stable tag: ${latest_tag}"
+              echo "Readme.txt preview: \n"
+              head -n 10 $README_TXT_PATH
