Revert "check file size"
This reverts commit f8a47e83e7d5c8d250873fa2fdaee25bb1a0d76f.

diff --git a/.github/workflows/css-file-check.yml b/.github/workflows/css-file-check.yml
--- a/.github/workflows/css-file-check.yml
+++ b/.github/workflows/css-file-check.yml
@@ -38,10 +38,22 @@ jobs:
         with:
           name: ${{ needs.build-plugin.outputs.artifact_name }}
           path: ./build
+      - name: Download hello-elementor theme
+        run: |
+          curl -L --output hello-elementor.zip "https://downloads.wordpress.org/theme/hello-elementor.zip"
+          unzip hello-elementor
+      - name: Debug
+        run: pwd
 
       - name: Install WordPress environment
         run: |
           npm run start-local-server
+
+      - name: List all files
+        run: ls -R
+
+      - name: List assets directory
+        run: ls -R assets/css || echo "Directory not found"
 
       - name: Check file sizes
         run: node ./tests/scripts/checkFileSize.js
