verify json structure before sending

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -92,6 +92,15 @@ jobs:
       - name: Run Playwright tests
         if: ${{ matrix.shardIndex != 'elements-regression' }}
         run: npm run test:playwright  -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=${{ inputs.reporter || 'list,github' }}
+      - name: Verify test-results.json structure
+        run: |
+          if [ -f tests/playwright/test-results.json ]; then
+            echo "test-results.json found. Displaying contents:"
+            cat tests/playwright/test-results.json | jq '.'
+          else
+            echo "test-results.json not found!"
+            exit 1
+          fi
       - name: Run element regression tests
         if: ${{ matrix.shardIndex == 'elements-regression' }}
         run: npm run test:playwright:elements-regression -- --reporter=${{ inputs.reporter || 'list,github' }}
